# Generated by Django 4.2.1 on 2023-05-18 15:11

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description_short', models.TextField(blank=True, verbose_name='Описание')),
                ('description_long', tinymce.models.HTMLField(blank=True, verbose_name='Текст')),
                ('custom_id', models.CharField(blank=True, max_length=25, verbose_name='Кастомный ID')),
                ('lng', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='places.place', verbose_name='Место')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
    ]
