# Generated by Django 4.2.1 on 2023-05-22 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('image', 'place')},
        ),
    ]
